### ISSUE TITLE
请问自部署的话对VPS的IP有没有要求?

### ISSUE THREAD

**Issue by ZevaXu** [imyuanx/chatgpt-proxy#11]
比如对于国外不能访问chat.openai.com的机房IP，需要在套一层cf warp吗

**Comment by imyuanx** [comment]
对出网 IP 是有要求的（IP 需要在 OpenAI 支持的国家列表中）
如果有 VPS 并且 IP 在 OpenAI 支持的国家列表中，那么自部署是最合适的
如果没有合适的 VPS 那么像你所说的办法也是可行的

**Comment by ZevaXu** [comment]
收到，谢谢！在VPS上部署了，确实挺好用的
