### ISSUE TITLE
VPS部署的是不是不支持SSE呢

### ISSUE THREAD

**Issue by Mydong** [imyuanx/chatgpt-proxy#13]
因为之前用[Zeabur]这个已经取消了，所以在VPS上弄了一下。
运行都是正常运行的。
但是，很明显不支持SSE模式；无法像之前一样 一个字一个字的输出

**Comment by imyuanx** [comment]
请问用的是 SSE 专用链接吗：`https://.../proxy-sse`
如果不是的话同步下最新代码

**Comment by winglight9** [comment]
支持的。
但是我在openAI Translator上使用sse报错。其他app都没问题。

**Comment by imyuanx** [comment]
> 支持的。 但是我在openAI Translator上使用sse报错。其他app都没问题。

有报错信息吗？可以通过右键插件图标 -> `Inspect Popup` 打开控制台查看报错信息

<img width="282" alt="image" src="https://user-images.githubusercontent.com/50652358/229395633-b3a05c14-81db-4eec-9bc0-3688d8ce2fe2.png">

**Comment by Mydong** [comment]
> 请问用的是 SSE 专用链接吗：`https://.../proxy-sse` 如果不是的话同步下最新代码

是的，今天我在重新拉取下试试。

**Comment by winglight9** [comment]
> 

我用的app，没有这个功能

**Comment by Mydong** [comment]
解决了 完美
