### ISSUE TITLE
如何手动部署

### ISSUE THREAD

**Issue by HePingLaoSan** [imyuanx/chatgpt-proxy#15]
不想通过docker，如果手动部署的话，可以怎么操作呢？感谢

**Comment by imyuanx** [comment]
新增了手动部署的教程

https://github.com/imyuanx/chatgpt-proxy/blob/main/README-CN.md#1-%E5%B0%86%E6%AD%A4%E4%BB%93%E5%BA%93-pull-%E5%88%B0%E6%9C%AC%E5%9C%B0
