### ISSUE TITLE
使用SSE有报错

### ISSUE THREAD

**Issue by zzy-life** [imyuanx/chatgpt-proxy#16]
![image](https://user-images.githubusercontent.com/68179477/235293175-3057c29b-dac1-438b-beb9-6fcff0e656f8.png)

**Comment by zzy-life** [comment]
好吧 是这个平台不支持SSE

**Comment by zzy-life** [comment]
不确定是不是digitalocean不能使用SSE，是因为docker的原因吗

**Comment by imyuanx** [comment]
可以提供下原请求吗？

**Comment by zzy-life** [comment]
是数字海洋的问题，和这个库无关



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月30日(周日) 上午9:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [imyuanx/chatgpt-proxy] 使用SSE有报错 (Issue #16)




 
可以提供下原请求吗？
