### ISSUE TITLE
我已经部署在zeabur，但是还是不会用

### ISSUE THREAD

**Issue by feixiangdao** [imyuanx/chatgpt-proxy#2]
有没有具体一点的配置
部署完后在哪里配置API？Variables？那key的名字是什么？
我已经生成了二级域名，但是打开后404

**Comment by imyuanx** [comment]
你好，部署完成后应该可以看到以下页面，其中`Your proxy link:`后面的链接收到请求以后会转发至`https://api.openai.com`

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/50652358/223607280-66ce86d8-e2e6-47b1-9b0c-520e3f260194.png">

稍后我会补充一个详细的说明

**Comment by feixiangdao** [comment]
你这个截图看域名是部署在Vercel，我部署在zeabur会不会有什么问题，打开域名就是404

**Comment by imyuanx** [comment]
你好👋，写了一份详细的操作流程，如果还有疑问可以继续回复

https://github.com/imyuanx/chatgpt-proxy/blob/main/README-CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by feixiangdao** [comment]
我就是按照这样的流程部署zeabur的，但是就是打开域名提示：404 page not found

**Comment by imyuanx** [comment]
如果可以的话，麻烦发一下你部署好的域名，我来看看是什么问题

**Comment by imyuanx** [comment]
看起来像是没有生成域名

麻烦按照第 7 步检查下是否已经生成域名了：
[7. 部署成功后，在 setting 选项卡下生成域名](https://github.com/imyuanx/chatgpt-proxy/blob/main/README-CN.md#%E5%9C%A8-zeabur-%E4%B8%8A%E9%83%A8%E7%BD%B2)

**Comment by feixiangdao** [comment]
不对啊，就是因为有生成了，才有这个域名的啊
![image](https://user-images.githubusercontent.com/18008211/224355725-9a5d7d98-bc08-4c41-9867-f3143fe4f8b3.png)

**Comment by feixiangdao** [comment]
神奇，我删除了重新生成一个域名，然后就可以了

**Comment by imyuanx** [comment]
那可能是 Zeabur 的问题，因为 Next.js 404 页面不是这个，解决了就好！
