### ISSUE TITLE
🔴 可用在「ChatGPTUnofficialProxyAPI」的「API_REVERSE_PROXY」吗？

### ISSUE THREAD

**Issue by Thomas-Harrell** [imyuanx/chatgpt-proxy#3]
> ChatGPTUnofficialProxyAPI 使用非官方代理服务器访问 ChatGPT 的后端API，绕过Cloudflare（使用真实的的ChatGPT，非常轻量级，但依赖于第三方服务器，并且有速率限制）

- [ChatGPTUnofficialProxyAPI](https://github.com/Chanzhaoyu/chatgpt-web#%E4%BB%8B%E7%BB%8D)

- [Reverse Proxy](https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy)

**Comment by imyuanx** [comment]
【不支持】这个项目的代理会转发到`api.openai.com`，适用于以上项目的`OPENAI_API_BASE_URL`字段
