### ISSUE TITLE
zeabur部署成功了，非SSE模式也成功了，但是SSE 模式不成功

### ISSUE THREAD

**Issue by Mydong** [imyuanx/chatgpt-proxy#7]
SSE模式不生效，好像是完全没有接通；

使用是这样的：
原接口：https://api.openai.com/v1/chat/completions

那么非sse的就是：https://自定义的.zeabur.app/proxy/v1/chat/completions
这个是生效的

sse的是：https://自定义的.zeabur.app/proxy-sse/v1/chat/completions

但是这个是接不通的

**Comment by imyuanx** [comment]
你的理解是完全没错的，但需要注意的是，你给出的链接中多了一个斜杠：`zeabur.app//proxy-sse` 中的 `//`

我在 `OpenAI Translator` 中实测 SSE 链接是生效的，如果你确认链接没错并且还是不生效的话，麻烦告知一下你用的是什么应用，我来测试一下

**Comment by Mydong** [comment]
> 你的理解是完全没错的，但需要注意的是，你给出的链接中多了一个斜杠：`zeabur.app//proxy-sse` 中的 `//`
> 
> 我在 `OpenAI Translator` 中实测 SSE 链接是生效的，如果你确认链接没错并且还是不生效的话，麻烦告知一下你用的是什么应用，我来测试一下

不好意思 上面的链接是我手打加复制的，多了一个/。  测试的时候，链接没有贴错。

我是用这个作者开源的项目搭建的。
https://github.com/zmlix/chatgpt-web

另外，昨晚搭建了您的项目外，还搭建了另外一个项目 x-dr/chatgptProxyAPI  ，使用cf work  作为备用。
这个的SSE在上述项目中，运行正常。

以上。感谢你们。

**Comment by imyuanx** [comment]
谢谢你的反馈，目前已经修复❤️

**Comment by Mydong** [comment]
> 谢谢你的反馈，目前已经修复❤️

感谢。


请问  zeabur 这个要怎么更新呢，是重新删除在搭建吗？

**Comment by Mydong** [comment]
> 谢谢你的反馈，目前已经修复❤️
谢谢，重新fork后，自动就更新了，给力！！
